security:
    providers:            
        our_db_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login                
                use_referer: true
                failure_path: login_failure_route_name
            logout:
                path: security_logout
                target: login

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
    encoders:
        App\Entity\User:
            algorithm: bcrypt